### ISSUE TITLE
Push modding library to Nuget

### ISSUE THREAD

**Issue by corygehr** [lvgamedev/simairport-modding#1]
Having the compiled Modding library available via Nuget would make it much easier for developers to grab the latest versions and test changes against their published mods. Also, with edge versions, being able to choose 'unreleased' versions would help with checking compatibility with changes being made on the 'edge' branch, for example.

**Comment by cal3432** [comment]
https://www.nuget.org/packages/SAML/

Consider done, @joscha999 if you want to edit some info just tell me.

**Comment by cal3432** [comment]
I am going to compile to nuget soon

**Comment by ghost** [comment]
https://www.nuget.org/packages/SimAirport.Modding/1.0.0
