### ISSUE TITLE
BUG-  my Remote security Monitor without staff , is not used by pax

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#101]
At moment the security minitor without staff  (stafftyp : 0 )  is not used by pax
![image](https://user-images.githubusercontent.com/56348209/82219237-46d9c680-991d-11ea-98a3-be58b78bf83e.png)

**Comment by modair1000** [comment]
It looks it not accepts my staff typ: 0   ,  because it normaly have a staff (security)

**Comment by modair1000** [comment]
[SecurityMonitor.zip](https://github.com/lvgamedev/simairport-modding/files/4808553/SecurityMonitor.zip)

**Comment by joscha999** [comment]
Fixed with the next edge deploy
