### ISSUE TITLE
Requesting full POconfig for Toilets

### ISSUE THREAD

**Issue by chick10000** [lvgamedev/simairport-modding#102]
I looked at the code and got the basics but there is way more going on.  It seems there are 2 markers. One for queue and one in front of toilet.  There are 2 sprite the toilet and the door.  I can add both but the door does not disappear when suppose to open.  So not sure if a naming convention needs to be used.

Thank you

**Comment by joscha999** [comment]
Base game toilet (raw export), please add any useful info to the wiki if you have a moment!
[toilet.zip](https://github.com/lvgamedev/simairport-modding/files/4808612/toilet.zip)
