### ISSUE TITLE
BUG ?  - Bodyscanner Config not works for Bodyscanners , only for metal detectors

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#105]
I made a Bodyscanner , but the pax just go endless up and down in it.
It looks like there is a marker missing 
I have the markers  exit + entry inside  as reciver type 2+3

**Comment by modair1000** [comment]
![image](https://user-images.githubusercontent.com/56348209/83014370-dfa7ca80-a01e-11ea-9d17-1cac064300ec.png)

**Comment by modair1000** [comment]
[NewBodyscanner.zip](https://github.com/lvgamedev/simairport-modding/files/4808563/NewBodyscanner.zip)

**Comment by joscha999** [comment]
body scanners need an additional marker called "scan"
