### ISSUE TITLE
BUG - the portal Config only works at texture size 2x3  but i need 3x3 for a elevator

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#110]
I made a elevator , with 3x3 , it not works , after i changed the wide to 2 it works , but then the walls around not fits 
![image](https://user-images.githubusercontent.com/56348209/83963910-7c812800-a8a9-11ea-958d-0d643b591d4a.png)

**Comment by modair1000** [comment]
[Elevator.zip](https://github.com/lvgamedev/simairport-modding/files/4837319/Elevator.zip)

**Comment by joscha999** [comment]
Moving the right markers by one will fix the auto foundation but the base will still be a staircase / escalator.
