### ISSUE TITLE
modded toilets

### ISSUE THREAD

**Issue by chick10000** [lvgamedev/simairport-modding#116]
modded toilets do not satisfy the requirements for a rest room zone, but if I place 1 in game toilet in the zone with modded toilets requirements are satisficed and all works well.   Note:  Attached textures still are work in progress.  
[toilet.zip](https://github.com/lvgamedev/simairport-modding/files/4810007/toilet.zip)
lls go around toilets

**Comment by joscha999** [comment]
Fixed with next edge deploy
