### ISSUE TITLE
At Baggage Scanner the trays not dissapier at the scan area  

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#119]
Also with right marker setting , it not works , trays are to see at the whole mod.   (at POConfig_BagScannerUtility)
and the trays have wrong orientation
(i post that for **MARINEANUKOTILAH** , because his account here not works anymore)
[RemoteBagScannerSmall.zip](https://github.com/lvgamedev/simairport-modding/files/4841078/RemoteBagScannerSmall.zip)

![image](https://user-images.githubusercontent.com/56348209/85929757-a5e51080-b8b7-11ea-9a29-7acf237b87d1.png)

**Comment by joscha999** [comment]
Added an extra field to the bag scanner utility named "maskSprite" - set it to the name of the sprite that should be used for masking, facings and large will automatically be added.

For masking name "myMask" the large bag scanner facing to the left will use the texture "myMask_Large_Left".
