### ISSUE TITLE
outside floor

### ISSUE THREAD

**Issue by marineanukotilah** [lvgamedev/simairport-modding#127]
[OutsideTile.zip](https://github.com/lvgamedev/simairport-modding/files/4872868/OutsideTile.zip)
outside floor (mod) is not visable if you are at 2nd or 3th level
the ingame ramp is visable if you are at level 2 or 3
![image](https://user-images.githubusercontent.com/57940866/86508371-d78e3800-bddf-11ea-8c93-f626e7241d19.png)
![image](https://user-images.githubusercontent.com/57940866/86508378-e2e16380-bddf-11ea-8a17-58fb1d078d5d.png)

**Comment by modair1000** [comment]
![image](https://user-images.githubusercontent.com/56348209/86530906-2b228380-bebd-11ea-86c1-07928b636da1.png)

with setting  1 at renderlayer   it is also to see in level 2+3

![image](https://user-images.githubusercontent.com/56348209/86530927-57d69b00-bebd-11ea-8fbb-65840c9cb7a1.png)
