### ISSUE TITLE
Add Agent proxy

### ISSUE THREAD

**Issue by corygehr** [lvgamedev/simairport-modding#2]
I'm looking for a way that I can both access existing Agents and create new ones in the game - by 'create', I mean I want to develop new Agent types. I could see a 'placeable' component to it but really, these make more sense as compiled mods since their behavior requires more definition.

Any Agent behaviors would also likely need more available access to the objects already on a Map to refine that behavior and then define where they should travel and how they should behave once they arrive at a destination point.

**Comment by ghost** [comment]
Add a reference to AssemblyCSharp.dll in the SimAirport_Data folder. This will allow you to access all the methods/classes the game has.

**Comment by ghost** [comment]
There is an agent class with lots of useful methods.

You can use ilspy/decompiler to view the classes.
