### ISSUE TITLE
Config for ProductDisplay isn't working

### ISSUE THREAD

**Issue by ghost** [lvgamedev/simairport-modding#24]

**Comment by joscha999** [comment]
Please provide a description, we can't work with a simple "xy doesn't work here".

Please at least provide the exception from your log, in a best case we'd also like to see a mod to test on, this way we can fix it faster.

**Comment by FinFuz** [comment]
![ProductDisplay](https://user-images.githubusercontent.com/40382753/69970013-28763f00-1526-11ea-92ae-038ad33bb10f.JPG)

**Comment by joscha999** [comment]
The product display seems to always need a retail object "POConfig_RetailObject", I added the requirement to the wiki, thanks for reporting!
