### ISSUE TITLE
issue mod modding

### ISSUE THREAD

**Issue by marineanukotilah** [lvgamedev/simairport-modding#29]
i have change my markers but in game the markers not show for my gate
my plane keeps being at taxi way
while all my markers are set 
![image](https://user-images.githubusercontent.com/57940866/70321400-84430f80-1827-11ea-8995-d38b5acb009e.png)
the markers for gate i get from joscha
center marker does not work by me and loading/unloading pax marker is also not working

**Comment by joscha999** [comment]
Markers are wrongly positioned mostly.
