### ISSUE TITLE
baggage depot creates  3 crazy things 

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#31]
1. It creates a foundaition in level G , when i build it in level -1 (pictures)
2. The Producer and Consumer are still shown after i connect it , and they work
3. The Baggage cars Trailers , are not to see in level -1
![Screenshot (609)](https://user-images.githubusercontent.com/56348209/70338363-16114380-184d-11ea-9759-d004209c869d.png)
and this :
![Screenshot (610)](https://user-images.githubusercontent.com/56348209/70338408-2d503100-184d-11ea-90e4-ddc5599bbc79.png)

**Comment by modair1000** [comment]
also in my new baggage depot (mod is at you joscha) , also the roads not works correct left/right of the depot (only left right direction works , up/down not) ,  and i can not build the coveyor inside the baggage depot (there is enough space to build it)(other things can build there)

**Comment by cal3432** [comment]
does the texture sizes match the width and height and if they do, check if your texture is being moved so the left side of it is touching the end of the sprite box. If they do, adjust the x and y of the texture in the json

**Comment by cal3432** [comment]
+ the ground level foundation is set in the PO_Config part of your json. It may take a fiddle with to get it right.

**Comment by modair1000** [comment]
[BaggagedepotG.zip](https://github.com/lvgamedev/simairport-modding/files/4030584/BaggagedepotG.zip)

**Comment by modair1000** [comment]
above is the complete mod ,  like you told me

**Comment by joscha999** [comment]
1. Fixed
2. Fixed
3. Moved to internal tracker since it's a base game issue

Roads: Fixed
Conveyor on placeable: Won't fix for the moment, just add some graphic and move the endpoints
