### ISSUE TITLE
At stafflimit only 0 and 1 are possible in the configs  , we also need 2 or more

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#33]
In all Configs that use  stafflimit , you only can say  -1 (1 staff) or 0 (zero staff)  ,(all others not work)  but we also need the possibility to do  2 staff or more.    
that problem we have at all Configs that use stafflimit

**Comment by joscha999** [comment]
Turns out stafflimit is not hooked up at all, no matter what value is used the game will ignore it.

It's now hooked up so setting it to anything > 0 should work with the upcoming edge build.
