### ISSUE TITLE
WE need all markers/tag for every Config , could you add this please ?

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#36]
At moment we have the configs , but not the needed markers (only some)  It would be good if you could add all needed markers for every Config.    Also at some Configs a bit more explanation. Like for example:  For stairs/escalator config ,  how we can do the json for     different levels , with what kind of markers.

**Comment by modair1000** [comment]
otherwise we always need to ask you (Joscha)

**Comment by joscha999** [comment]
Duplicate of #27
