### ISSUE TITLE
Enable/Disable mods in the Mod Editor UI.

### ISSUE THREAD

**Issue by qcs2017** [lvgamedev/simairport-modding#37]
With more Script mods coming up, we will need a way to enable/disable mod functionality without a subscription/unsubscription to the mod. There should be a checkbox/on-off-toggle in the Mod Editor UI for it, and it should save its settings through quit/restart.

Thanks :-)

**Comment by joscha999** [comment]
Implemented on the edge branch on simairport.modding.
Will be up on the game side with the next edge deploy.
