### ISSUE TITLE
Instructions for workshop uploading clearer

### ISSUE THREAD

**Issue by NALStudio** [lvgamedev/simairport-modding#40]
It would be more clear if you put the instructions of uploading to workshop to the inbuilt method (Main Menu --> Mods --> General Mod --> [ModToPublish] --> Upload to workshop) and not the SteamCMD method.

**Comment by cal3432** [comment]
Or it would be better if there was a seperate menu eg:

Menu --> Mods 

Mods --> Browse Mods --> ... view mods ect.

Mods --> Upload a mod

**Comment by NALStudio** [comment]
> 
> 
> Or it would be better if there was a seperate menu eg:
> 
> Menu --> Mods
> 
> Mods --> Browse Mods --> ... view mods ect.
> 
> Mods --> Upload a mod

Yeah... Just making the instructions point to the game's mod uploader and not SteamCMD would make it easier for newcomers since I didn't know there was an inbuilt method until... I think it was modair who told me.
