### ISSUE TITLE
My Example mod

### ISSUE THREAD

**Issue by NALStudio** [lvgamedev/simairport-modding#41]
Fixed Version:
[EXAMPLE MOD.zip](https://github.com/lvgamedev/simairport-modding/files/4017471/EXAMPLE.MOD.zip)

Ps. If you need any help with the wiki, I can gladly help.

**Comment by cal3432** [comment]
Thanks nal! Will add it to the pages soon.

**Comment by cal3432** [comment]
Il compile a dummy script mod and add to it

**Comment by NALStudio** [comment]
Ok. Should I close this thread?
