### ISSUE TITLE
Mods should be able to delete old settings

### ISSUE THREAD

**Issue by qcs2017** [lvgamedev/simairport-modding#43]
The SettingManager can only add settings.
If I had a setting I do not wish to have anymore, I can stop adding it, but it keeps popping up, without being referenced.
I think we should have a way to delete an old setting which we do not need. Alternatively, only show up settings which are explicitly added via SettingManager. Not sure which one is more correct.

**Comment by joscha999** [comment]
Added a remove function, also fixed TryGetSetting and GetOrDefault - will be up with the next edge build.
