### ISSUE TITLE
Hanger menu does not scale past 5 entries

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#48]
That is a problem of the menu there.   here some pictures
![Screenshot (649)](https://user-images.githubusercontent.com/56348209/71898228-0b521300-3159-11ea-8cb3-def5bef33f4c.png)
![Screenshot (650)](https://user-images.githubusercontent.com/56348209/71898231-0c834000-3159-11ea-92e3-6c0400bcb609.png)

**Comment by modair1000** [comment]
The menu should be able to handle up to 20 Slots

**Comment by joscha999** [comment]
This will be up with the next deploy, hangar menu supports up to 20 vehicles and will auto resize, it'll ignore anything past 20!
