### ISSUE TITLE
ability to collect funds from a pax using an object

### ISSUE THREAD

**Issue by chick10000** [lvgamedev/simairport-modding#5]
Add component config that can be configured to any price for an object like arcade or vending.  For example a vibrating chair could cost $1 for every time a pax uses it. also the ability to say what category the funds go to.

![arcade](https://user-images.githubusercontent.com/57146944/67786628-991cce00-fa45-11e9-8f6c-b1637d62d56f.png)
objects.

**Comment by modair1000** [comment]
You can do that with electronics vending config , or arcade Config , i think

**Comment by joscha999** [comment]
Since there's already configs for some stuff I'd rewrite the request to
- Add component config that can be configured to any price and any need.

Having just a config that takes money will mean no pax will ever use it.

**Comment by chick10000** [comment]
closed not needed at this time
