### ISSUE TITLE
I think we need more categorys(with atlas) in the mods foulder

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#50]
At moment the atlas becomes very full ,  i think we need more.
Maybe we can use category's in the mods folder,  with a atlas for each of them.
Like that also a outdoor atlas would be possible (for better colors) .
Otherwise the quality will be not so good anymore 
(Just a idea)

**Comment by ghost** [comment]
Multiple atlases has been implemented in the release of SimAirport.
