### ISSUE TITLE
Possibility to to Parking and Hangars(as vehicle depots) also in level -1 and -2

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#54]
I want to do a Parking and also a airside vehicle parking(with Hangar config)  in level -1/-2 
but the hangar not accepts the road in level -1/-2 ,  and the parking needs ground. 
So it would be nice , if you could make both possible.   Thank you :)   

(PS:  Just ideas)

**Comment by joscha999** [comment]
Fixed on the next edge build
