### ISSUE TITLE
Baggage scanner Mod with Bag Scanner Utility Config not works

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#55]
1. My new baggage scanner Mod not works , only some pax use it , and then they go out of the airport all too the left down (near road) and then back , and then it happens again. 
2. also the bins are not to see
3. The security zone has a warning if i want to use only this baggage scanner (it not accepts it) 
![image](https://user-images.githubusercontent.com/56348209/72523504-40005180-3860-11ea-964c-f4da7879fb0f.png)
![image](https://user-images.githubusercontent.com/56348209/72523513-468ec900-3860-11ea-9a57-24b9c95e8779.png)
![image](https://user-images.githubusercontent.com/56348209/72523529-4ee70400-3860-11ea-8358-7983556a0cac.png)

**Comment by modair1000** [comment]
i tried it now also as remote baggage scanner , but same problems

**Comment by joscha999** [comment]
Added needed markers to the wiki, bins will probably work once markers are set.
