### ISSUE TITLE
Since the new atlas , some Mod icons have white lines  

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#61]
but the template has no lines ,  maybe that is because the atlas looks different
![image](https://user-images.githubusercontent.com/56348209/72986567-bcf37400-3de8-11ea-901b-3a401ed334d4.png)
![image](https://user-images.githubusercontent.com/56348209/72986576-c41a8200-3de8-11ea-9d97-c521093b83e0.png)

**Comment by modair1000** [comment]
like at the ATC Tower as example

**Comment by joscha999** [comment]
This should be fixed with the changes made on stream, please test and report back.
