### ISSUE TITLE
Need the vendor Object Config more markers ? or a second config ?

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#68]
I ask that because i made a PizzaHut Kiosk , but i can not build it , but in json + Log are no errors to see. Also the texture works. So i think there are missing markers , or i need a second config with it.
[PizzaHut.zip](https://github.com/lvgamedev/simairport-modding/files/4142797/PizzaHut.zip)
I tried that mod also with a other config(hunger) , then i can build it , but it still has problems :

**Comment by modair1000** [comment]
Found the Problem , i also need the Hunger Config

**Comment by joscha999** [comment]
[Bar.zip](https://github.com/lvgamedev/simairport-modding/files/4841238/Bar.zip)
