### ISSUE TITLE
BUG - Problem with sorting order at backview at walls

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#70]
I want to update my vending machines , that they fit to the in-game ones.  But i have a problem at the backview.  I need a low sorting number that the vending is behind the wall , but then the pax are full to see .    Like here:
![image](https://user-images.githubusercontent.com/56348209/73826615-6893bf80-47fe-11ea-904a-fe03216763c2.png)

Here you see it :   The pax are in front of the vending(cocacola vending) , but the wall is still in behind the vending.  How i can do it like the in-game vending ? **Also at a sorting order of -1000(at the vending)  the wall is still not in front.**   That looks like a bug (maybe)

**Comment by modair1000** [comment]
[CocaCola_Vending.zip](https://github.com/lvgamedev/simairport-modding/files/4841190/CocaCola_Vending.zip)


Like you see at the screenshot , the ingame iteams are behind the wall , all mods infront of wall (also with high sorting order no change)

**Comment by joscha999** [comment]
To get attaching to walls to work set the sprite back to x,y 0,0 (i.e. no offset at all), then add the property 9 (AttachToWall) to your properties (in your PO Config).
