### ISSUE TITLE
ID Check Mod and Metal detector Mod not accepted by zone (FAILED ERROR)

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#73]
![image](https://user-images.githubusercontent.com/56348209/73929760-b4fdfe80-48d5-11ea-9ec7-3f25672491db.png)
Like you see here , the ID check Mod and the metal detector Mod are in the zone , but it not accepts it , and still shows a missing warning

**Comment by joscha999** [comment]
Like I wrote on discord this will be fixed with the next edge deploy.
