### ISSUE TITLE
modded sidewalks to work outside secure area

### ISSUE THREAD

**Issue by chick10000** [lvgamedev/simairport-modding#74]
the in game sidewalks work outside in a secure area.  The modded sidewalks do not.

**Comment by joscha999** [comment]
Why? Please provide as much information and possibly an example mod.

**Comment by chick10000** [comment]
![image](https://user-images.githubusercontent.com/57146944/77124935-a6e5e680-6a1a-11ea-9d62-271c52d395dd.png)

The smoking area was created using base game sidewalks.  I would like to design some smoking area sidewalks for the area.  currently only base game sidewalks will work.  using terrain tools to create the sidewalks.  modded Sidewalks currently work in non-secure areas outside

**Comment by joscha999** [comment]
Added "isWalkableSecureOutside" as a bool field to constructionMaterial, when set to true it'll behave the same as the base game sidewalk.
