### ISSUE TITLE
modded floor tiles has space between tiles

### ISSUE THREAD

**Issue by chick10000** [lvgamedev/simairport-modding#75]
using 64X63 .png graphic for floor tiles and black space appears between tiles which is different than in game tiles that have no space.  the topic has been discussed when creating the new atlas just want to make sure issue is up.

![spacing](https://user-images.githubusercontent.com/57146944/74265375-73ec5c80-4cd0-11ea-90fc-3eb1b26fe6b1.png)

**Comment by BR146** [comment]
It's connected with #87: The atlas' filter mode uses bilinear interpolation creating those lines. Changing the filter mode as described in #87, the lines go away:
![RendererFloorTiles](https://user-images.githubusercontent.com/65818738/82734169-496f5e00-9d19-11ea-97f2-d25d6164d1c3.png)

**Comment by joscha999** [comment]
Fixed in the next edge version
