### ISSUE TITLE
modded pa speaker floor tile

### ISSUE THREAD

**Issue by chick10000** [lvgamedev/simairport-modding#78]
Since there really is no ceiling to place a pa speaker a user suggested the ability to make a floor tile a PA speaker that is walkable.  

requesting a config that can be added to the terrain tool to mod a tile as a pa speaker and the ability to connect it to an amp.

I tried adding POConfig_PASystemEmitter to terrain tool config and it did not work as intended

**Comment by chick10000** [comment]
[floor_PA_speaker.zip](https://github.com/lvgamedev/simairport-modding/files/4210435/floor_PA_speaker.zip)

**Comment by joscha999** [comment]
Will not be implemented, terrain tools (construction materials) and placeables are two way too different systems to interchange or use components on each other.

You can still mod it as a placeable, pax will just avoid moving over it.
