### ISSUE TITLE
At my new Remote Bus Pickup  in LEVEL  -1  , the doors are not accepted

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#80]
![Screenshot (826)](https://user-images.githubusercontent.com/56348209/75447786-54109600-596a-11ea-9845-072d042e890f.png)
the door positions are correct , but the game not accept the doors in level -1/-2

**Comment by modair1000** [comment]
![Screenshot (827)](https://user-images.githubusercontent.com/56348209/75448490-9b4b5680-596b-11ea-98ac-3874cdbd1ce6.png)

i also have this error in the log

**Comment by joscha999** [comment]
Tested with the base game remote bus pickup (now works indoors too) - no issue.
Check if yours works overground (I assume it doesn't) and check your marker placement.
