### ISSUE TITLE
The cafe zone not accepts my Self Service cashregister    as  cash register

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#89]
![image](https://user-images.githubusercontent.com/56348209/79420488-4e721c80-7fb9-11ea-80c0-e0afe0d7f047.png)
with a second Standart cash register in , it works ,   so the zone just not accept the self cash register.

**Comment by joscha999** [comment]
Fixed with the next edge deploy, zone was checking for a placeable with name "Cash Register" instead of the config, now correctly checks for the config.
