### ISSUE TITLE
Parking Json Settings  for ParkingGarages    

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#91]
It would be great to have a json setting at the new parking system , for parking garages.
At moment i need 3 position settings for every car (entry/exit/lot) , It would be good to have also a setting where you can say  this position should use  a number of cars  (like 0-50)  or it would be extrem hard to do a jsons for parking garages .

**Comment by modair1000** [comment]
I just think about that a bit ,  you also can not see the cars in garages , so i just need a setting with the capacity (0-50) ,  and the income ,  maybe as a 2. version of the parking system ?

**Comment by joscha999** [comment]
won't be implemented // any parking garage should be build by the users themselfs
