### ISSUE TITLE
BUG - Problem with Mod amplifiers , it often shows it needs a functional electric zone , but the ingame ones work

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#94]
There is also a functional zone there
the crazy thing is , if you change the floor and build it again it works
but after reload of the save the problem is there again

**Comment by modair1000** [comment]
[AudiosystemPack.zip](https://github.com/lvgamedev/simairport-modding/files/4598942/AudiosystemPack.zip)

**Comment by modair1000** [comment]
If you need a save with that problem , i have one from a user
[rtha26-test.airport.zip](https://github.com/lvgamedev/simairport-modding/files/4599071/rtha26-test.airport.zip)
There you see the problem , at the electric zone near the baggage claim.

**Comment by joscha999** [comment]
Fixed in the next edge deploy, also fixed for existing saves
