### ISSUE TITLE
Flight.OnArrival not adding money onto lifetimestats.mTerminalUsageRev

### ISSUE THREAD

**Issue by TBFLash** [lvgamedev/simairport-modding#98]
It looks like the code that should add money onto lifetimestats.mTerminalUsageRev is adding onto mRwyUsageRev instead. mRwyUsageRev is added to twice in the OnArrival method. dnSpy Screenshot below.

![image](https://user-images.githubusercontent.com/63376880/81885825-30bcb680-9569-11ea-9bf0-2f48ad18b588.png)

**Comment by joscha999** [comment]
Fixed with next edge deploy
