### ISSUE TITLE
BUG - Arcade Mod is not accepted by arcadezone

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#99]
I made my first arcade Mod , but the arcade zone not accepts it as arcade game
i used the POConfig_ArcadeGameUtility, Assembly-CSharp
![image](https://user-images.githubusercontent.com/56348209/82124934-c2633880-97a2-11ea-9d36-c720d7c9a09f.png)

**Comment by joscha999** [comment]
Fixed with the next edge deploy
